### PR TITLE
fix: remove some packages that use react-spring

### LINKED ISSUE #25: Review the use of react-spring and remove it if possible
Currently being used in spinner and footer packages

### PR DESCRIPTION
**Pull request by gazpachu**
- Removed footer and gallery
- Refactored spinner to avoid react-spring
- Modal dialog still uses react-spring (no peer dep)

Fixes #25

### CODE REVIEW

File: packages/package-namespace/src/PackageNamespace.ts [hunk 1]
```diff
@@ -9,9 +9,7 @@ export enum PackageNamespace {
   Calendar = 'calendar',
   Checkbox = 'checkbox',
   Enzyme = 'enzyme',
-  Footer = 'footer',
```
Comment (wahidmagdy) [inline packages/package-namespace/src/PackageNamespace.ts:12]: Can we get confirmation that Footer/Gallery are not in use by any project and it's okay to delete them?

File: packages/spinner/src/__tests__/index.tsx [hunk 2]
```diff
@@ -18,38 +18,6 @@ describe('Spinner', () => {
       const wrapper = mount(<Spinner />);
       expect(wrapper.find(SpinnerContainer)).toHaveLength(1);
     });
```
Comment (wahidmagdy) [inline packages/spinner/src/__tests__/index.tsx:20]: `isCompleting` prop has been removed, so test name should be changed

**Review by wahidmagdy — CHANGES_REQUESTED** [review]
Generally good, just worried about removing packages or introducing breaking changes in `Spinner`

File: packages/package-namespace/src/PackageNamespace.ts (hunk 1 above)
Comment (gazpachu) [reply packages/package-namespace/src/PackageNamespace.ts:12]: They are being used in the Diner app, but it uses an old version of Tablekit. We won't be updating that app to use the latest version of TK. We are already working on a new Diner app

File: packages/spinner/src/__tests__/index.tsx (hunk 2 above)
Comment (gazpachu) [reply packages/spinner/src/__tests__/index.tsx]: fixed

**Review by wahidmagdy — APPROVED** [review]

File: packages/modal-dialog/package.json [hunk 3]
```diff
@@ -21,14 +21,14 @@
...
-    "@tablecheck/tablekit-utils": "^0.1.0"
+    "@tablecheck/tablekit-utils": "^0.1.0",
+    "react-spring": ">=9.0.0-rc.3 <10"
   },
   "peerDependencies": {
     "@emotion/react": ">=11.4 <12",
     "@emotion/styled": ">=11.3 <12",
     "react": ">=16.8.0 <18",
-    "react-dom": ">=16.2.0 <18",
-    "react-spring": ">=9.0.0-rc.3 <10"
```
Comment (SimeonC) [inline packages/modal-dialog/package.json:31]: Please leave this as a peer dependency.

File: packages/spinner/src/Spinner.tsx [hunk 4]
```diff
@@ -11,66 +10,27 @@ export type PropsType = VariantProps<
...
-    /** Time in milliseconds after component mount before spinner is visible.
-     * Note: this currently doesn't work until react-spring v9 is released  */
-    delay?: number;
-
-    /** Whether the process is complete and the spinner should leave */
-    isCompleting?: boolean;
-
-    /** Handler for once the spinner has completed its outro animation */
-    onComplete?: () => void;
-
```
Comment (SimeonC) [inline packages/spinner/src/Spinner.tsx:23]: Removing API on a component is a breaking change. Please change the label and commit to correctly reflect this.

**Review by SimeonC — CHANGES_REQUESTED** [review]
Left some comments that need addressing.

File: packages/modal-dialog/package.json (hunk 3 above)
Comment (gazpachu) [reply packages/modal-dialog/package.json:31]: If we leave it as peer dependency, the main package.json will have to include the dep and therefore all projects using TK will have to use it as well, isn't it?

Comment (gazpachu) [reply packages/modal-dialog/package.json:31]: I'll have a look and see if we can remove it from modal-dialog as well

Comment (SimeonC) [reply packages/modal-dialog/package.json:31]: No that's incorrect. Dependencies are not used in the project unless they are imported, whether they are peer dependencies or not. We use a peer dependency to avoid duplicate versions and the issues that come with that.

This peer dependency means that the `modal-dialog` package requires you to install react-spring alongside it. It does not mean that if you are using a tablekit component that you need react-spring. This is the point of the monorepo, all the different packages have their own dependencies and requirements.

About bundling react-spring, if you don't use react-spring in the rest of your project and do `import('tablekit-modal-dialog')` then react-spring will be code split _with_ the modal dialog code.

Comment (gazpachu) [reply packages/modal-dialog/package.json]: Fixed

File: packages/spinner/src/Spinner.tsx (hunk 4 above)
Comment (gazpachu) [reply packages/spinner/src/Spinner.tsx:23]: Fixed

**Comment by gazpachu** [comment]
@SimeonC there seems to be a CI issue with the npm authentication

**Review by SimeonC — APPROVED** [review]
